name: MLOps Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Download code from repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest httpx matplotlib seaborn

      - name: Set up CML
        uses: iterative/setup-cml@v2

      - name: Train model and generate CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python train.py
          
          # This command tells CML to take our markdown file and drop it in the PR!
          cml comment create metrics.md

      - name: Run Pytest
        run: pytest -v

  build-and-deploy:
    if: github.event_name == 'push'
    needs: test-code
    runs-on: ubuntu-latest
    steps:
      - name: Download code from repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-api:latest